### PR TITLE
add a handy alias for TOMLDecodeError

### PR DESCRIPTION
**Pull request by graingert**
no offence taken if you don't want this - but I think it's worth it!

### CODE REVIEW

**Comment by hukkin** [comment]
Cheers!

But I think I'd rather keep public API to its minimum. Upper cased TOML was chosen for PEP8 compliance and for parity with e.g. `JSONDecodeError` in the stdlib.

**Comment by graingert** [comment]
@hukkin is this your first rejected PR?

**Comment by hukkin** [comment]
:smile: I had to check. The answer is [no](https://github.com/hukkin/tomli/pull/19). But yeah all the rest are my own :smile:

**Comment by hukkin** [comment]
And yeah, to further explain myself, I definitely do see the value of this, but there are like 5 somewhat reasonable TOML libraries for Python, and merging this would set a bad precedent for aliasing all of their APIs.

**Comment by graingert** [comment]
> And yeah, to further explain myself, I definitely do see the value of this, but there are like 5 somewhat reasonable TOML libraries for Python, and merging this would set a bad precedent for aliasing all of their APIs.

yeah agreed, It's better to fix all the usages

**Pull request closed without merging**
