### PR TITLE
Add test coverage for text mode error

### PR DESCRIPTION
**Pull request by hauntsaninja**
Error message was added in https://github.com/hukkin/tomli/pull/175

### CODE REVIEW

**Comment by hukkin** [comment]
Thanks!

It seems you did add a test in https://github.com/hukkin/tomli/pull/175 (tests/test_misc.py/test_incorrect_load). Should we add the error message assertion in that one instead?

That test should also probably live in the test_error.py file, but since it deviates us from cpython/tomllib I'm not sure it's worth moving it.

**Review by hauntsaninja — COMMENTED** [review]
Ah, good point. I added the message in the location of the existing test. If we want to move it that's fine too (I can make the corresponding change in CPython)

**Comment by hukkin** [comment]
If you have the energy to move it in CPython, let's do it here too in this PR! If not then this LGTM.

**Comment by hukkin** [comment]
I'll actually just merge this now. We can consider moving the test separately.

**Pull request merged**
