### PR TITLE
Types improvements

### PR DESCRIPTION
**Pull request by Viicos**

### CODE REVIEW

**Comment by hukkin** [comment]
Hey there!

I don't want to actively break Python 3.7 yet, or deviate from cpython/tomllib for little benefit, so closing this.

**Comment by Viicos** [comment]
Hi @hukkin,

The minimum Python version is set in the metadata:

https://github.com/hukkin/tomli/blob/4e245a4bbbefed99e550e196095ea65c851cf31d/pyproject.toml#L13

Meaning the library _can't_ possibly be installed on 3.7.

**Comment by Viicos** [comment]
Regarding the deviation from the stdlib, understandable, I can also open a PR to cpython to parametrize the patterns?

**Comment by hukkin** [comment]
> Meaning the library can't possibly be installed on 3.7.

Someone could theoretically package it for a distro despite the metadata, change the metadata themselves and test that 3.7 still works, or whatever. The main purpose of this repo currently is to be a backport of tomllib, so perhaps it makes sense to be extra conservative.

> Regarding the deviation from the stdlib, understandable, I can also open a PR to cpython to parametrize the patterns?

I assume cpython may not appreciate such a PR since it doesn't run mypy against tomllib, the type annotations are there only because they were inherited from here. Might be best to avoid the busywork. Especially since they annotate private API, and are not incorrect, simply not as narrow as they could be.

**Comment by encukou** [comment]
> I assume cpython may not appreciate such a PR since it doesn't run mypy against tomllib

That is indeed the case, though it might change in the future. (It's not straightforward politically, but also technically since type-checkers ignore stdlib's annotations and use typeshed instead.)

**Comment by Viicos** [comment]
> That is indeed the case, though it might change in the future. (It's not straightforward politically, but also technically since type-checkers ignore stdlib's annotations and use typeshed instead.)

Was about to say that as well. [pyright can't resolve the `tomllib._re` module](https://pyright-play.net/?pythonVersion=3.12&strict=true&locale=en-us&reportUninitializedInstanceVariable=true&code=JYWwDg9gTgLgBDCIA2zgCMB0B9KBTTEAQxgGMALbRbAExLxlDwFgAoNoA), although it works through Pylance for some reason:

image

Anyway, happy to revisit in the future.

**Pull request closed without merging**
