### PR TITLE
Update GitHub actions

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
This could be somehow automated using Dependabot:
[Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)

### CODE REVIEW

**Comment by hukkin** [comment]
I appreciate the PR, but this is something that I will do with https://github.com/asottile/all-repos to all my repos, in an automated fashion.

**Comment by DimitriPapadopoulos** [comment]
But does it work at all? I mean, [actions/setup-python](https://github.com/actions/setup-python/tags) is still stuck at `v2` while `v3` was released in April and `v4` a month ago.

**Comment by hukkin** [comment]
setup-python is at v3 and is working just fine, as can be seen from recent CI runs: https://github.com/hukkin/tomli/actions

**Comment by DimitriPapadopoulos** [comment]
My wrong, somehow I got it all mixed up. Indeed, [actions/setup-python](https://github.com/actions/setup-python/tags) was changed in May from `v2` to `v3` by 7e563eed5286b5d46b8290a9f56a86d955b23a9a, **after `v3`** was released in April and **before `v4`** was released in October.

**Pull request closed without merging**
